version: '3'
services:
    redis:
        image: "redis:alpine"

    higlass:
        depends_on:
            - "redis"
            - "certbot"
        image: "higlass/higlass-docker:v0.6.1"
        ports:
            - 80:80
            - 443:443
        volumes:
            - /data/hg-data/:/data
            - /data/hg-tmp/:/tmp
            - /data/certbot/conf:/etc/letsencrypt
            - /data/certbot/www:/var/www/certbot
              # - ./web-context/sites-enabled:/etc/nginx/sites-enabled
            - ./web-context/sites-enabled/hgserver_nginx.conf:/etc/nginx/sites-enabled/hgserver_nginx.conf
        environment:
            - REDIS_HOST=redis
            - SITE_URL=server.gosling-lang.org
            - WORKERS=10
        container_name: "higlass-container"
    certbot:
        image: certbot/certbot
        volumes:
            - /data/certbot/conf:/etc/letsencrypt
            - /data/certbot/www:/var/www/certbot
              # - ./web-context:/etc/nginx
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
